### PR TITLE
change_UT_cases_to_triton

### PR DESCRIPTION
**Pull request by RUIJIEZHONG66166**

### CODE REVIEW

**Comment by chuanqi129** [comment]
Quick question, how do you prepare triton ut scripts now? If we have a scripts to insert ipex into triton ut directly, we can move this put in the workflow directly, and put the convert script into our `.github/scripts/` folder. We need make our tests more and more transparent.
cc @Stonepia

**Comment by Stonepia** [comment]
Hello @chuanqi129
For this part, @RUIJIEZHONG66166  has already prepared the script locally. I agree that we could put that script into `.github/scripts` and call that in CI. Maybe @RUIJIEZHONG66166  could help to make that script public?

**Review by Stonepia — APPROVED** [review]
The overall process is OK to me. Let's first setup the CI process and refine the output with another pr.

**Review by EikanWang — APPROVED** [review]

**Comment by chuanqi129** [comment]
@RUIJIEZHONG66166 @Stonepia For ATSM/ARC UT setup, we also can leverage this method to prepare a scripts to help skip FP64 cases. Please follow it.

**Pull request merged**
