### PR TITLE
Runner 0.0.18

### PR DESCRIPTION
**Pull request by pbchekin**
GitHub runner image with PTDB 0.5.2.

### CODE REVIEW

**Comment by whitneywhtsang** [comment]
is PTDB 0.5.2 now officially released?

**Comment by pbchekin** [comment]
> is PTDB 0.5.2 now officially released?

Yes: https://www.intel.com/content/www/us/en/developer/articles/release-notes/gpu-dependencies-for-pytorch-release-notes.html

**Review by whitneywhtsang — APPROVED** [review]

**Comment by YarShev** [comment]
@pbchekin, @whitneywhtsang, does PTDB 0.5.2 support ubuntu 24.04? or 22.04 only?

**Comment by whitneywhtsang** [comment]
> @pbchekin, @whitneywhtsang, does PTDB 0.5.2 support ubuntu 24.04? or 22.04 only?

Only 22.04 is specified in https://www.intel.com/content/www/us/en/developer/articles/release-notes/gpu-dependencies-for-pytorch-release-notes.html. Triton requirement is 22.04 too: https://github.com/intel/intel-xpu-backend-for-triton?tab=readme-ov-file#compatibility.

**Pull request merged**
