### PR TITLE
Fix headers path for conda run

### PR DESCRIPTION
**Pull request by leshikus**
Subj

### CODE REVIEW

**Comment by pbchekin** [comment]
Please take a look to https://github.com/intel/intel-xpu-backend-for-triton/blob/main/.github/workflows/pip-test.yml.
It works without oneAPI and without copying headers and libraries.

**Comment by leshikus** [comment]
The conda run uses a different compiler, and this compiler has different defaults. This simpler variant could replace `no-basekit` testrun. For conda I need either to copy things, change the driver (which supplies -I parameters to the compiler) or use variables like `CPATH`. Can go with any of these variants.

**Comment by leshikus** [comment]
just adding `pip install intel-sycl-rt intel-pti` didn't work, will have to dig further

**Comment by pbchekin** [comment]
> just adding `pip install intel-sycl-rt intel-pti` didn't work, will have to dig further

You may need to set `LD_LIBRARY_PATH`. There is a helper script https://github.com/intel/intel-xpu-backend-for-triton/blob/main/scripts/sycl_rt_lib.py, that can be used for that, for example:

```
LD_LIBRARY_PATH:=$LD_LIBRARY_PATH:$(python scripts/sycl_rt_lib.py)
```

In `pip-test.yml` this is not required because `actions/setup-python` sets `LD_LIBRARY_PATH`. For conda you may need to this explicitly.

**Comment by anmyachev** [comment]
@pbchekin @leshikus What's the plan with this pull request?

**Comment by pbchekin** [comment]
Closing now, will revisit later.

**Pull request closed without merging**
