### PR TITLE
Add attention adv path benchmark

### PR DESCRIPTION
**Pull request by ESI-SYD**
As Attention's functionality fix landed.

### CODE REVIEW

**Comment by ESI-SYD** [comment]
https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10765521676

**Comment by ESI-SYD** [comment]
Depends on https://github.com/intel/intel-xpu-backend-for-triton/pull/2160

**Comment by quintinwang5** [comment]
> Depends on #2160

merged.

**Comment by ESI-SYD** [comment]
Success: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10766931602

**Review by whitneywhtsang — APPROVED** [review]

**Comment by Dewei-Wang-sh** [comment]
what's the perf now?

**Comment by whitneywhtsang** [comment]
> what's the perf now?

https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10766931602 contains performance.

**Comment by quintinwang5** [comment]
> > what's the perf now?
> 
> https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10766931602 contains performance.

After revert `7410ea38cc5beaa2d273b4e7f40e43f602d2c145`, you can get normal performance.

**Comment by Dewei-Wang-sh** [comment]
> https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10766931602

@quintinwang5   still perf gap

**Pull request merged**
