### PR TITLE
Moved TritonToTritonGPUWarpPass from lib/ to third_party/intel

### PR DESCRIPTION
**Pull request by hwnam831**
TritonToTritonGPUWarpPass has moved from lib/Conversion to third_party/intel.
Headers and CMakeLists.txt files are fixed accordingly.

### CODE REVIEW

**Review by whitneywhtsang — COMMENTED** [review]
Can you please also make changes like https://github.com/intel/intel-xpu-backend-for-triton/pull/1011 to TritonToTritonGPUWarpPass?

**Comment by hwnam831** [comment]
I have changed the code to make TabelGen automatically generate constructors with options

**Review by etiotto — COMMENTED** [review]
I think we should structure the directories in a way to resemble MLIR upstream: 
```
third_party/include/Conversion/Passes.td (contains all conversion passes definitions in tablegen format)
third_party/include/Conversion/Passes.h (includes TritonToTritonGPUWarp.h )
third_party/include/Conversion/CMakeLists.txt
third_party/include/Conversion/TritonToTritonGPUWarp
third_party/include/Conversion/TritonToTritonGPUWarp/TritonToTritonGPUWarp.h


```

**Review by whitneywhtsang — APPROVED** [review]

**Comment by whitneywhtsang** [comment]
> I think we should structure the directories in a way to resemble MLIR upstream:
> 
> ```
> third_party/include/Conversion/Passes.td (contains all conversion passes definitions in tablegen format)
> third_party/include/Conversion/Passes.h (includes TritonToTritonGPUWarp.h )
> third_party/include/Conversion/CMakeLists.txt
> third_party/include/Conversion/TritonToTritonGPUWarp
> third_party/include/Conversion/TritonToTritonGPUWarp/TritonToTritonGPUWarp.h
> ```

@hwnam831 Please address this comment for all conversion passes in another PR.

**Pull request merged**
