### PR TITLE
Setup micro benchmarks for non-gemm kernels

### PR DESCRIPTION
**Pull request by LiyangLingIntel**
Setup micro benchmarks to check performance regressions for non-gemm Triton kernels.

Current kernel cases are picked from internal hand-written Triton kernels. I add a `benchmark` function for each of them.
Kernels that are with `tt.dot`, have bugs and may have potential copyright issue, are skipped for this pull request.

More kernels will be added in next step to expand the coverage.

### CODE REVIEW

**Review by pbchekin — APPROVED** [review]

**Review by etiotto — COMMENTED** [review]
Can you also run a way to test the microbmks from `test-truton.sh` ?

**Comment by LiyangLingIntel** [comment]
> @LiyangLingIntel can you also run a way to test the microbmks from `test-triton.sh` ?

Added a new option `--benchmarks` in test-triton.sh for micro benchmarks.

**Comment by etiotto** [comment]
@LiyangLingIntel what is the status of these benchmarks. Are they all passing ? They aren't added to the CI, do you plan to add them to CI ?

**Comment by pbchekin** [comment]
> @LiyangLingIntel what is the status of these benchmarks. Are they all passing ? They aren't added to the CI, do you plan to add them to CI ?

I would suggest keeping a GitHub workflow as is: if i understand correctly, the workflow is triggered daily (nightly) and it also can be triggered manually for a specific branch. I think it should be OK for now.

**Comment by LiyangLingIntel** [comment]
> @LiyangLingIntel what is the status of these benchmarks. Are they all passing ? They aren't added to the CI, do you plan to add them to CI ?

The target of these benchmarks are to check the performance regression regularly. I agree with Paval's opinion, keeping a daily workflow to run them is OK for now.

BTY, we do not verify the correctness in these benchmarks, as they're for performance checking. 
If it's better to have these, I can add them later.

**Comment by etiotto** [comment]
@LiyangLingIntel is this one still blocked?

**Comment by LiyangLingIntel** [comment]
> @LiyangLingIntel is this one still blocked?

Yes. For the micro-benchmark structure part, it's been merged in https://github.com/intel/intel-xpu-backend-for-triton/pull/1202.
@vlad-penkin Do you have any feedbacks on the license issue of these handwritten kernels?

**Comment by etiotto** [comment]
@vlad-penkin this has been open for a while any update or should we close this one ?

**Comment by LiyangLingIntel** [comment]
If we are not going to merge this PR recently, I think we can close it for now. At lease the microbenchmark structure has already been merged in https://github.com/intel/intel-xpu-backend-for-triton/pull/1202. 
We can find suitable micro kernels from other sources when there are further requirements.

**Pull request closed without merging**
