### PR TITLE
Skip 4 tests for conda environment.

### PR DESCRIPTION
**Pull request by pbchekin**
See #936.

### CODE REVIEW

**Comment by pbchekin** [comment]
Successful run for "Conda build and test": https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/8767303328

**Review by whitneywhtsang — COMMENTED** [review]
Do you know why conda environment would have more failures?

**Comment by pbchekin** [comment]
> Do you know why conda environment would have more failures?

@leshikus do you have ideas?

**Review by leshikus — APPROVED** [review]
LGTM

**Comment by leshikus** [comment]
Hey @whitneywhtsang 

I cannot say for sure; each problem like this needs a software developer to debug; let me list some known causes
1) the conda environment has different library versions, this may affect some tests,
2) intel compiler has some conda-specific bugs,
3) you fixed the memory access bug here, https://github.com/intel/intel-xpu-backend-for-triton/issues/672

**Pull request merged**
