### PR TITLE
Add Python 3.12 to the CI test matrix

### LINKED ISSUE #1018: [UT][CI] Add Python 3.12 to daily validation matrix and / or to CI checks on PR merge
Initial proposal is not to run full Python validation matrix (3.9, 3.10, 3.11, 3.12) for each PR but do it daily.

Few notes:
- Python validation matrix should match current PyTorch validation matrix
- Python support version matrix should follow PyTorch policy, more details [here](https://github.com/pytorch/pytorch/issues/120718)), which follows [NEP 29 policy](https://numpy.org/neps/nep-0029-deprecation_policy.html)

### PR DESCRIPTION
**Pull request by pbchekin**
Fixes #1018.

### CODE REVIEW

**Comment by whitneywhtsang** [comment]
Do we have any successfully CI run with Python 3.12?

**Comment by pbchekin** [comment]
> Do we have any successfully CI run with Python 3.12?

Not yet. Turns out that the pinned version of `tokenizers`, a Python packages required for E2E test, does not have published wheels for Python 3.12. I am going to disable E2E  test for Python 3.12 temporary.

**Comment by pbchekin** [comment]
> Do we have any successfully CI run with Python 3.12?

Successful run: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10014207269

**Review by leshikus — APPROVED** [review]
LGTM

**Pull request merged**
