### PR TITLE
Fixes #1607

### LINKED ISSUE #1607: E2E accuracy infra_error for GoogleFnet, huggingface, training, float32, LTS+Rolling, PyTorch
LTS: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/9894739846/job/27333002744#step:26:51
Rolling: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/9895211262/job/27334594600#step:26:57

```
Unexpected target architecture
UNREACHABLE executed at /runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/third_party/intel/lib/Analysis/DPAS.cpp:80!
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  libtriton.so         0x00007f0b68eeca27
1  libtriton.so         0x00007f0b64debb49
2  libtriton.so         0x00007f0b68eea4ac
3  libtriton.so         0x00007f0b68eed0ff
4  libc.so.6            0x00007f0c49312520
5  libc.so.6            0x00007f0c493669fc pthread_kill + 300
6  libc.so.6            0x00007f0c49312476 raise + 22
7  libc.so.6            0x00007f0c492f87f3 abort + 211
8  libtriton.so         0x00007f0b68e4ec41
9  libtriton.so         0x00007f0b647b6837
10 libtriton.so         0x00007f0b6491f4c2
11 libtriton.so         0x00007f0b6491f2f8
12 libtriton.so         0x00007f0b65040366
13 libtriton.so         0x00007f0b65040cb1
14 libtriton.so         0x00007f0b6504347b
15 libtriton.so         0x00007f0b64ce0f3e
16 libtriton.so         0x00007f0b64d4ea89
17 libtriton.so         0x00007f0b64d3e136
18 libtriton.so         0x00007f0b64d36adc
19 libtriton.so         0x00007f0b64d36b44
20 libtriton.so         0x00007f0b64c758c6
21 libpython3.10.so.1.0 0x00007f0c49677132
22 libpython3.10.so.1.0 0x00007f0c49650f7f _PyObject_MakeTpCall + 127
23 libpython3.10.so.1.0 0x00007f0c495869fe
24 libpython3.10.so.1.0 0x00007f0c496b61ec _PyEval_EvalFrameDefault + 20956
25 libpython3.10.so.1.0 0x00007f0c496b0236
26 libpython3.10.so.1.0 0x00007f0c496b61ec _PyEval_EvalFrameDefault + 20956
27 libpython3.10.so.1.0 0x00007f0c496b0236
28 libpython3.10.so.1.0 0x00007f0c496b1367 _PyEval_EvalFrameDefault + 855
29 libpython3.10.so.1.0 0x00007f0c496b0236
30 libpython3.10.so.1.0 0x00007f0c496522fd PyObject_Call + 397
31 libpython3.10.so.1.0 0x00007f0c496b3e6e _PyEval_EvalFrameDefault + 11870
32 libpython3.10.so.1.0 0x00007f0c496b0236
33 libpython3.10.so.1.0 0x00007f0c496b1737 _PyEval_EvalFrameDefault + 1831
34 libpython3.10.so.1.0 0x00007f0c496b0236
35 libpython3.10.so.1.0 0x00007f0c496530b1
36 libpython3.10.so.1.0 0x00007f0c496b2490 _PyEval_EvalFrameDefault + 5248
37 libpython3.10.so.1.0 0x00007f0c496b0236
38 libpython3.10.so.1.0 0x00007f0c49756a24
39 libpython3.10.so.1.0 0x00007f0c496b1367 _PyEval_EvalFrameDefault + 855
40 libpython3.10.so.1.0 0x00007f0c496b0236
41 libpython3.10.so.1.0 0x00007f0c49756a24
42 libpython3.10.so.1.0 0x00007f0c496b3e6e _PyEval_EvalFrameDefault + 11870
43 libpython3.10.so.1.0 0x00007f0c496b0236
44 libpython3.10.so.1.0 0x00007f0c496b3e6e _PyEval_EvalFrameDefault + 11870
45 libpython3.10.so.1.0 0x00007f0c496b0236
46 libpython3.10.so.1.0 0x00007f0c496b1737 _PyEval_EvalFrameDefault + 1831
47 libpython3.10.so.1.0 0x00007f0c496b0236
48 libpython3.10.so.1.0 0x00007f0c496530b1
49 libpython3.10.so.1.0 0x00007f0c496b2490 _PyEval_EvalFrameDefault + 5248
50 libpython3.10.so.1.0 0x00007f0c496b0236
51 libpython3.10.so.1.0 0x00007f0c496b1737 _PyEval_EvalFrameDefault + 1831
52 libpython3.10.so.1.0 0x00007f0c496b0236
53 libpython3.10.so.1.0 0x00007f0c49651b57 _PyObject_Call_Prepend + 215
54 libpython3.10.so.1.0 0x00007f0c4968a489
55 libpython3.10.so.1.0 0x00007f0c496872f3
56 libpython3.10.so.1.0 0x00007f0c49650f7f _PyObject_MakeTpCall + 127
57 libpython3.10.so.1.0 0x00007f0c496b64ce _PyEval_EvalFrameDefault + 21694
58 libpython3.10.so.1.0 0x00007f0c496b0236
[59](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/9894739846/job/27333002744#step:26:60) libpython3.10.so.1.0 0x00007f0c496b61ec _PyEval_EvalFrameDefault + 20956
60 libpython3.10.so.1.0 0x00007f0c496b0236
61 libpython3.10.so.1.0 0x00007f0c496b1737 _PyEval_EvalFrameDefault + 1831
62 libpython3.10.so.1.0 0x00007f0c496b0236
63 libpython3.10.so.1.0 0x00007f0c496b1737 _PyEval_EvalFrameDefault + 1831
64 libpython3.10.so.1.0 0x00007f0c496b0236
65 libpython3.10.so.1.0 0x00007f0c496b1737 _PyEval_EvalFrameDefault + 1831
66 libpython3.10.so.1.0 0x00007f0c496b0236
67 libpython3.10.so.1.0 0x00007f0c496b1367 _PyEval_EvalFrameDefault + 855
68 libpython3.10.so.1.0 0x00007f0c496b0236
69 libpython3.10.so.1.0 0x00007f0c496b1737 _PyEval_EvalFrameDefault + 1831
70 libpython3.10.so.1.0 0x00007f0c496b0236
71 libpython3.10.so.1.0 0x00007f0c49651b57 _PyObject_Call_Prepend + 215
72 libpython3.10.so.1.0 0x00007f0c4968a489
73 libpython3.10.so.1.0 0x00007f0c496872f3
74 libpython3.10.so.1.0 0x00007f0c49650f7f _PyObject_MakeTpCall + 127
75 libpython3.10.so.1.0 0x00007f0c496b64ce _PyEval_EvalFrameDefault + 21694
76 libpython3.10.so.1.0 0x00007f0c496b0236
77 libpython3.10.so.1.0 0x00007f0c496b1367 _PyEval_EvalFrameDefault + 855
78 libpython3.10.so.1.0 0x00007f0c496b0236
79 libpython3.10.so.1.0 0x00007f0c4972a214 PyEval_EvalCode + 148
80 libpython3.10.so.1.0 0x00007f0c4973fbd4
81 libpython3.10.so.1.0 0x00007f0c4973fb5b
82 libpython3.10.so.1.0 0x00007f0c495f665c
83 libpython3.10.so.1.0 0x00007f0c495f63ad _PyRun_SimpleFileObject + 905
84 libpython3.10.so.1.0 0x00007f0c495f74ef _PyRun_AnyFileObject + 136
85 libpython3.10.so.1.0 0x00007f0c49748c55 Py_RunMain + 981
86 libpython3.10.so.1.0 0x00007f0c4974870d Py_BytesMain + [61](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/9894739846/job/27333002744#step:26:62)
87 libc.so.6            0x00007f0c492f9d90
88 libc.so.6            0x00007f0c492f9e40 __libc_start_main + 128
89 python               0x000055a1a203d095 _start + 37
```

### PR DESCRIPTION
**Pull request by etiotto**

### CODE REVIEW

**Review by whitneywhtsang — APPROVED** [review]
We should still investigate why on a PVC machine, the architectural is not PVC.
@pbchekin Please verify if this changes #1607.

**Comment by etiotto** [comment]
> We should still investigate why on a PVC machine, the architectural is not PVC. @pbchekin Please verify if this fixes #1607.

We think it should fix it but pls confirm.

**Comment by pbchekin** [comment]
> We think it should fix it but pls confirm.

Yes, this fixes the issue, thanks!
https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/9898113826/job/27344175864#step:29:58

**Review by pbchekin — APPROVED** [review]

**Comment by pbchekin** [comment]
> We should still investigate why on a PVC machine, the architectural is not PVC.

Right, also it would be nice to add a test for that, if possible.

**Pull request merged**
