### PR TITLE
Update SYCL device library

### PR DESCRIPTION
**Pull request by whitneywhtsang**

### CODE REVIEW

**Comment by whitneywhtsang** [comment]
> @whitneywhtsang could you show diff in text format?

The diff is huge, I basically regenerated the file with the new dpcpp compiler.

**Comment by whitneywhtsang** [comment]
Attached the diff in text format: [diff.txt](https://github.com/user-attachments/files/17835546/diff.txt)

**Review by pbchekin — APPROVED** [review]

**Comment by whitneywhtsang** [comment]
> Do we have any documentation on how and when to do this?

No, ideally we should get the device library from dpcpp directly, we have a compiler ticket for that.

**Comment by anmyachev** [comment]
> > Do we have any documentation on how and when to do this?
> 
> No, ideally we should get the device library from dpcpp directly, we have a compiler ticket for that.

Is this option supposed to work with other compilers? (having `sycl` runtime only)

I don't insist, but if describing the process takes about 10 minutes, then it's a probably a good idea do it and put doc file next to `.bc` file.

**Comment by whitneywhtsang** [comment]
Yes. The instruction is not very clean, but I can try to create one, in the meantime while we need to create device library ourselves.

**Comment by whitneywhtsang** [comment]
Created one in https://github.com/intel/intel-xpu-backend-for-triton/pull/2788.

**Pull request merged**
