### PR TITLE
Deprecate fast prefetch implementation

### PR DESCRIPTION
**Pull request by whitneywhtsang**
The optimization is implemented in IGC, and it is already disabled in Triton for one agama release, so this PR removes it.

### CODE REVIEW

**Review by etiotto — APPROVED** [review]

**Review by chengjunlu — APPROVED** [review]

**Comment by Dewei-Wang-sh** [comment]
what form of tritongen prefetch op we should generate to leverage IGC's fast prefetch?

**Comment by whitneywhtsang** [comment]
> what form of tritongen prefetch op we should generate to leverage IGC's fast prefetch?

When array length is 2, IGC optimization would change it to 1 and increase the tile width.
So the current form in both paths seem fine.

**Comment by Dewei-Wang-sh** [comment]
> > what form of tritongen prefetch op we should generate to leverage IGC's fast prefetch?
> 
> When array length is 2, IGC optimization would change it to 1 and increase the tile width. So the current form in both paths seem fine.

then later we can remove array length in Tritongen to simplify.

**Review by Dewei-Wang-sh — APPROVED** [review]

**Comment by whitneywhtsang** [comment]
> then later we can remove array length in Tritongen to simplify.

Do you mind elaborating on this idea? In TritonGEN, I would imagine, we want to let users to use array length 1 or 2, but IGC would change array length from 2 to 1 for faster performance.

**Comment by Dewei-Wang-sh** [comment]
> > then later we can remove array length in Tritongen to simplify.
> 
> Do you mind elaborating on this idea? In TritonGEN, I would imagine, we want to let users to use array length 1 or 2, but IGC would change array length from 2 to 1 for faster performance.

it's straightforward that user only cares about the prefetch size like 8x32. 
whether the array length 1 or 2 to get best perf, it's decided by IGC.
User do not need to know this array length info.

**Comment by whitneywhtsang** [comment]
> > > then later we can remove array length in Tritongen to simplify.
> > 
> > 
> > Do you mind elaborating on this idea? In TritonGEN, I would imagine, we want to let users to use array length 1 or 2, but IGC would change array length from 2 to 1 for faster performance.
> 
> it's straightforward that user only cares about the prefetch size like 8x32. whether the array length 1 or 2 to get best perf, it's decided by IGC. User do not need to know this array length info.

oic what you mean, user of TritonGEN should not care of array length. However, that would make the lowering of TritonGEN 2d block prefetch more complicated, as it would need to determine what is supported in OpenCL C extension, and lower to those. Let's revisit this idea when we transfer to using SPIR-V extension.

**Pull request merged**
