### PR TITLE
Reland upstream commit `15c5e55`

### LINKED ISSUE #2603: Reland upstream commit `15c5e55`
Reland https://github.com/intel/intel-xpu-backend-for-triton/commit/15c5e5519ff129104956ef0a726656f9e5cb4359 that is temporarily reverted in https://github.com/intel/intel-xpu-backend-for-triton/pull/2595 by https://github.com/intel/intel-xpu-backend-for-triton/commit/77f98f00658988d59626b50bf946159b3a3ad5f3.

### PR DESCRIPTION
**Pull request by anmyachev**
Closes #2603

### CODE REVIEW

**Comment by anmyachev** [comment]
@whitneywhtsang I'm not sure that there is a need to reland this commit given your changes in https://github.com/intel/intel-xpu-backend-for-triton/pull/2615. What do you think?

**Comment by whitneywhtsang** [comment]
> @whitneywhtsang I'm not sure that there is a need to reland this commit given your changes in #2615. What do you think?

Sounds good, let's close https://github.com/intel/intel-xpu-backend-for-triton/issues/2603.

**Comment by whitneywhtsang** [comment]
@anmyachev Just noticed that there are more changes reverted in https://github.com/intel/intel-xpu-backend-for-triton/commit/77f98f00658988d59626b50bf946159b3a3ad5f3, should we handle those changes outside of `ConvertLayoutOpToLLVM.cpp` as well?

**Comment by anmyachev** [comment]
> @anmyachev Just noticed that there are more changes reverted in [77f98f0](https://github.com/intel/intel-xpu-backend-for-triton/commit/77f98f00658988d59626b50bf946159b3a3ad5f3), should we handle those changes outside of `ConvertLayoutOpToLLVM.cpp` as well?

Indeed, my mistake: let's continue in https://github.com/intel/intel-xpu-backend-for-triton/pull/2624

**Pull request closed without merging**
