### PR TITLE
Merge OpenAI Triton commit `78c8054`

### PR DESCRIPTION
**Pull request by anmyachev**
This PR change the Triton base from https://github.com/intel/intel-xpu-backend-for-triton/commit/152ef2deb8852d5c84f9ffba217b3a7c8f398c5f to https://github.com/intel/intel-xpu-backend-for-triton/commit/78c8054298a81f578dcd8c79b519981c57dfb665 (Oct 27).
Pass rate: `99.84%`

Please do not squash and merge this PR.

Repeating https://github.com/intel/intel-xpu-backend-for-triton/pull/2595.

### CODE REVIEW

**Review by arunjose696 — APPROVED** [review]

**Comment by anmyachev** [comment]
@whitneywhtsang @pbchekin `Create a merge commit` option seems to be disabled for this repository. How do I merge this pull request without squashing?

**Comment by pbchekin** [comment]
> @whitneywhtsang @pbchekin `Create a merge commit` option seems to be disabled for this repository. How do I merge this pull request without squashing?

Yes, usually we enable merge commits temporary for PRs like this.

**Comment by whitneywhtsang** [comment]
> @whitneywhtsang @pbchekin `Create a merge commit` option seems to be disabled for this repository. How do I merge this pull request without squashing?

We can always use command line to merge instead of UI.

**Comment by whitneywhtsang** [comment]
FYI @anmyachev, usually I remove the second half of the auto-generated message from like `Merge commit '78c8054298a81f578dcd8c79b519981c57dfb665' into amyachev
/merge0` to `Merge commit '78c8054298a81f578dcd8c79b519981c57dfb665'`, so we don't mention our personal branch name.

**Pull request merged**
