### PR TITLE
Merge OpenAI Triton commit `76ed94d`

### PR DESCRIPTION
**Pull request by whitneywhtsang**
This PR change the Triton base from 185299e204ea6e163cc717da137526939002659b to 76ed94df1924b2262be9b37d778b6e0ccccb1180 (Oct 18).
Pass rate: 98.99%

Please do not squash and merge this PR.

### CODE REVIEW

**Review by etiotto — APPROVED** [review]

**Review by pbchekin — APPROVED** [review]

**Comment by alexbaden** [comment]
Trying a PyTorch Inductor run as this contains the commit that changes `AttrsDescriptor` again: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11481885630

**Comment by whitneywhtsang** [comment]
> Trying a PyTorch Inductor run as this contains the commit that changes `AttrsDescriptor` again: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11481885630

I reverted that commit, as it requires special handling, so this PR doesn't contain changes to `AttrsDescriptor`.

**Comment by alexbaden** [comment]
I have started working on adapting to those changes in PyTorch as part of my effort to land the `__repr__` string representation of `AttrsDescriptor` in upstream. Is there an issue to re-land this commit?

**Comment by whitneywhtsang** [comment]
> I have started working on adapting to those changes in PyTorch as part of my effort to land the `__repr__` string representation of `AttrsDescriptor` in upstream. Is there an issue to re-land this commit?

There are some unit test failures that require investigation.

**Pull request merged**
