### PR TITLE
Fix regression issue in Triton front end for the argument with None as input.

### PR DESCRIPTION
**Pull request by chengjunlu**
A quick fix to make the torch inductor work with the Triton LLVM target on Intel GPU.

I will upstream the fix formally to Triton repo with regression cases.

### CODE REVIEW

**Comment by etiotto** [comment]
Where is the issue associated with this PR ? Create one if it does not exist and also create another one to remember to upstream.

**Comment by vlad-penkin** [comment]
I've linked an issue which track the fix.

@chengjunlu please create a new issue to track upstreaming.

**Review by whitneywhtsang — CHANGES_REQUESTED** [review]
https://github.com/intel/intel-xpu-backend-for-triton/pull/719 should have already fixed this issue.

**Comment by chengjunlu** [comment]
> #719 should have already fixed this issue.

Great. Close this PR and related issues.

**Pull request closed without merging**
