### PR TITLE
Change default threads per warp to 16

### PR DESCRIPTION
**Pull request by etiotto**

### CODE REVIEW

**Comment by etiotto** [comment]
Need to be rebased after PR #704 lands.

**Comment by etiotto** [comment]
Here is the performance impact on `02-fused-softmax.py` (the data reported is gbps - higher is better):

With 16 thread per warp:
```
1st run:
softmax-performance:
          N      Triton  Torch (native)  Torch (jit)
0     256.0   28.628456       26.296242    22.073006
1     384.0   38.978256       38.607577    31.850669
2     512.0   50.991844       50.552259    40.912061
3     640.0   62.561117       62.207164    49.457931
4     768.0   73.351714       72.946176    56.566515
..      ...         ...             ...          ...
93  12160.0  364.903422      364.903422   117.536935
94  12288.0  367.580773      372.855693   115.405895
95  12416.0  368.880684      371.692887   122.845155
96  12544.0  372.361605      370.959491   119.038475
97  12672.0  374.785113      371.230186   123.065745

[98 rows x 4 columns]

2nd run:
softmax-performance:
          N      Triton  Torch (native)  Torch (jit)
0     256.0   29.006078       26.296242    22.017755
1     384.0   39.064810       38.720879    31.850669
2     512.0   51.140076       50.515969    40.912061
3     640.0   62.605644       62.075462    49.333107
4     768.0   73.556179       72.946176    56.445517
..      ...         ...             ...          ...
93  12160.0  468.795982      474.384807   147.273323
94  12288.0  469.255310      478.834664   143.147132
95  12416.0  472.567723      480.958863   147.942438
96  12544.0  475.202379      482.922754   148.068384
97  12672.0  476.244577      482.311387   147.971658
```

With 32 threads per warp:
```
1st run:
softmax-performance:
          N      Triton  Torch (native)  Torch (jit)
0     256.0   29.030010       26.217863    22.017755
1     384.0   38.949489       38.607577    31.850669
2     512.0   50.991844       50.515969    40.840827
3     640.0   62.605644       62.207164    49.360791
4     768.0   73.402723       72.946176    56.445517
..      ...         ...             ...          ...
93  12160.0  329.052505      472.640745   145.694157
94  12288.0  323.658463      474.929657   142.027572
95  12416.0  355.953702      478.329936   146.086983
96  12544.0  375.688436      478.499648   146.278146
97  12672.0  314.799172      475.594325   146.626235

[98 rows x 4 columns]

2nd run:
softmax-performance:
          N      Triton  Torch (native)  Torch (jit)
0     256.0   28.910741       26.296242    22.073006
1     384.0   38.949489       38.607577    31.793107
2     512.0   50.844468       50.552259    40.912061
3     640.0   62.605644       62.031686    49.444030
4     768.0   73.351714       72.946176    56.415348
..      ...         ...             ...          ...
93  12160.0  463.594362      475.464488   147.059499
94  12288.0  464.480160      478.698940   144.192091
95  12416.0  467.134423      478.665371   147.329337
96  12544.0  469.252649      480.768051   147.593034
97  12672.0  454.317574      481.112270   147.146538

```

**Comment by whitneywhtsang** [comment]
@chengjunlu to look at the CI failures.

**Comment by chengjunlu** [comment]
A related PR https://github.com/intel/intel-xpu-backend-for-triton/pull/762

**Comment by etiotto** [comment]
We cannot change the default threads to 16 because several operators perform better with 32 threads per warp.

**Pull request closed without merging**
