### PR TITLE
xfail test_tensor_atomic_rmw for fp64 as unsupported type

### LINKED ISSUE #1548: A770 test_tensor_atomic_rmw failing on nightly run
```
FAILED language/test_core.py::test_tensor_atomic_rmw[shape3-0-1-float64] - RuntimeError: Triton Error [ZE]: 0x70000004
FAILED language/test_core.py::test_tensor_atomic_rmw[shape7-1-1-float64] - RuntimeError: Triton Error [ZE]: 0x70000004
FAILED language/test_core.py::test_tensor_atomic_rmw[shape11-0-1-float64] - RuntimeError: Triton Error [ZE]: 0x70000004
FAILED language/test_core.py::test_tensor_atomic_rmw[shape15-1-1-float64] - RuntimeError: Triton Error [ZE]: 0x70000004
FAILED language/test_core.py::test_tensor_atomic_rmw[shape19-0-1-float64] - RuntimeError: Triton Error [ZE]: 0x70000004
FAILED language/test_core.py::test_tensor_atomic_rmw[shape23-1-1-float64] - RuntimeError: Triton Error [ZE]: 0x70000004
FAILED language/test_core.py::test_tensor_atomic_rmw[shape27-0-1-float64] - RuntimeError: Triton Error [ZE]: 0x70000004
FAILED language/test_core.py::test_tensor_atomic_rmw[shape31-1-1-float64] - RuntimeError: Triton Error [ZE]: 0x70000004
FAILED language/test_core.py::test_tensor_atomic_rmw[shape35-0-1-float64] - RuntimeError: Triton Error [ZE]: 0x70000004
FAILED language/test_core.py::test_tensor_atomic_rmw[shape39-1-1-float64] - RuntimeError: Triton Error [ZE]: 0x70000004
FAILED language/test_core.py::test_tensor_atomic_rmw[shape43-0-1-float64] - RuntimeError: Triton Error [ZE]: 0x70000004
FAILED language/test_core.py::test_tensor_atomic_rmw[shape47-1-1-float64] - RuntimeError: Triton Error [ZE]: 0x70000004
```

### PR DESCRIPTION
**Pull request by YarShev**
Closes #1548.

### CODE REVIEW

**Comment by YarShev** [comment]
I am not sure if I should have updated all scripts/skiplist/*/language.txt files. Let me know if it is required and why.

**Review by alexbaden — COMMENTED** [review]
Will the existing free function work -

`def check_type_supported(dtype, device):`

**Comment by YarShev** [comment]
> Will the existing free function work -
> 
> `def check_type_supported(dtype, device):`

Good catch! I didn't notice it. Addressed.

**Review by alexbaden — APPROVED** [review]
👍🏻

**Comment by etiotto** [comment]
I think this change could be upstreamed to Triton. Can you give it a try @YarShev ?

**Comment by alexbaden** [comment]
Is there relevant AMD or NVIDIA hardware that does not support fp64? Otherwise I suspect they will reject the change.

**Pull request merged**
