### PR TITLE
Remove dot3d from xe2 skiplist

### PR DESCRIPTION
**Pull request by LiyangLingIntel**
There is no dot3d failures on LNL, I think we can remove it from xe2 skiplist.

### CODE REVIEW

**Comment by whitneywhtsang** [comment]
It was reported that they failed on Windows LNL. Is there CI testing for that? @pbchekin @gshimansky

**Comment by pbchekin** [comment]
> It was reported that they failed on Windows LNL. Is there CI testing for that? @pbchekin @gshimansky

Not yet, but Gregory can test it manually on Windows BMG.

**Comment by LiyangLingIntel** [comment]
> > It was reported that they failed on Windows LNL. Is there CI testing for that? @pbchekin @gshimansky
> 
> Not yet, but Gregory can test it manually on Windows BMG.

If there are indeed failures, please let me know how to reproduce so I can fix it.

**Comment by gshimansky** [comment]
I just checked and all language\test_core.py::test_dot3d* tests passed for me.

**Review by whitneywhtsang — APPROVED** [review]

**Pull request merged**
