### PR TITLE
Disable old GitHub workflow build_and_test

### PR DESCRIPTION
**Pull request by pbchekin**
The new workflow (build_and_test_2) works in parallel with the old one and shows the same results in terms of PR verification. At the same time:

* The old workflow does not scale, there is only one runner.
* The old workflow uses a persistent runner which is prone to side effects (for example, updating llvm affects all future runs).

Note that to merge this PR we need to update repository branch rules to make the new workflow required and remove the old workflow from required checks for PR.

### CODE REVIEW

**Comment by whitneywhtsang** [comment]
> Note that to merge this PR we need to update repository branch rules to make the new workflow required and remove the old workflow from required checks for PR.

Let's change the required check from the old workflow to the new workflow now.

I would like to wait till next week to approve this PR, to give Ettore a chance to review the new workflow before disabling the old workflow. And also we can observe if there are any unexpected differences in behavior of the two workflows in the meantime.

**Comment by pbchekin** [comment]
> Let's change the required check from the old workflow to the new workflow now.

Done

**Comment by etiotto** [comment]
I am OK with disable the old workflow (which was temporary anyway). Keep in mind though that eventually we should just run the upstream workflow here: https://github.com/openai/triton/blob/main/.github/workflows/integration-tests.yml

**Review by whitneywhtsang — APPROVED** [review]

**Comment by etiotto** [comment]
Given that we no longer need `build_and_test.yml` I think this PR should (a) remove that file and (b) rename `build_and_test_2.yaml` to  `build_and_test.yml` (let's use the yml suffix given that OpenAI upstream is sticking to that suffix ?).

**Pull request merged**
