### PR TITLE
Mark expected failures as xfail in test_core.py

### PR DESCRIPTION
**Pull request by whitneywhtsang**

### CODE REVIEW

**Review by pbchekin — APPROVED** [review]

**Review by etiotto — APPROVED** [review]
For future merges: I think the merge PR should take care of "xfailing" new tests that cause the pass rate to degrade and that are obvious limitations.

**Comment by whitneywhtsang** [comment]
> For future merges: I think the merge PR should take care of "xfailing" new tests that cause the pass rate to degrade and that are obvious limitations.

We can be more careful when doing merges, but it is not obvious that pass rate is degraded.

**Comment by etiotto** [comment]
> > For future merges: I think the merge PR should take care of "xfailing" new tests that cause the pass rate to degrade and that are obvious limitations.
> 
> We can be more careful when doing merges, but it is not obvious that pass rate is degraded.

It would help if the test script could detect degradations in pass rate and prevent merging it in that case.  The check should be "overwritable" in case the developer determines that new tests cannot be immediately fixed though.  @pbchekin WDYT?

**Comment by whitneywhtsang** [comment]
> It would help if the test script could detect degradations in pass rate and prevent merging it in that case. The check should be "overwritable" in case the developer determines that new tests cannot be immediately fixed as part of the merge PR. @pbchekin WDYT?

Maybe a file that record the current pass rate, and if it is expected to have degradation, then one need to change the content of the file. And automatically update the file if pass rate is higher?

**Comment by pbchekin** [comment]
> > It would help if the test script could detect degradations in pass rate and prevent merging it in that case. The check should be "overwritable" in case the developer determines that new tests cannot be immediately fixed as part of the merge PR. @pbchekin WDYT?
> 
> Maybe a file that record the current pass rate, and if it is expected to have degradation, then one need to change the content of the file. And automatically update the file if pass rate is higher?

I think it is too complex and fragile) I think the best approach is what Areg proposed: if a PR decreases pass rate after merging to the default branch, we just detect it and fix in a separate PR? The key point here is doing this fast.

**Comment by etiotto** [comment]
> > > It would help if the test script could detect degradations in pass rate and prevent merging it in that case. The check should be "overwritable" in case the developer determines that new tests cannot be immediately fixed as part of the merge PR. @pbchekin WDYT?
> > 
> > 
> > Maybe a file that record the current pass rate, and if it is expected to have degradation, then one need to change the content of the file. And automatically update the file if pass rate is higher?
> 
> I think it is too complex and fragile) I think the best approach is what Areg proposed: if a PR decreases pass rate after merging to the default branch, we just detect it and fix in a separate PR? The key point here is doing this fast.

OK, let's try to check the pass rate for degradation in merge PRs (manually) for now.

**Pull request merged**
