### PR TITLE
Remove `DeviceArch` dependency

### PR DESCRIPTION
**Pull request by whitneywhtsang**
2D block load or prefetch should work for other device architectures other than PVC, removing the limitations.

### CODE REVIEW

**Review by etiotto — APPROVED** [review]
The specific flags "support-sg-2d-block" is used to determine whether 2D block load/stores and prefetch operation are supported by the target GPU. So we no longer need to check the device arch string.

**Review by ZzEeKkAa — APPROVED** [review]
Thank you! Should we remove `DeviceArch` class and `getDeviceArch` method as well?

**Comment by ZzEeKkAa** [comment]
BTW, it should resolve #1496 . Just need to test

**Comment by ZzEeKkAa** [comment]
UPD: #1496 is now working even without this PR. So it can't be use to test this PR.

**Comment by whitneywhtsang** [comment]
> Thank you! Should we remove `DeviceArch` class and `getDeviceArch` method as well?

Sure, removed.

**Pull request merged**
