### PR TITLE
Update SPIRV-LLVM-Translator version

### PR DESCRIPTION
**Pull request by whitneywhtsang**

### CODE REVIEW

**Comment by whitneywhtsang** [comment]
@pbchekin Can we have an automated process to update SPIRV-LLVM-Translator version?

**Comment by pbchekin** [comment]
> @pbchekin Can we have an automated process to update SPIRV-LLVM-Translator version?

Sure. What do we need for update and how is it triggered?

**Comment by whitneywhtsang** [comment]
> > @pbchekin Can we have an automated process to update SPIRV-LLVM-Translator version?
> 
> Sure. What do we need for update and how is it triggered?

Find the last commit that can pass all Triton tests in https://github.com/KhronosGroup/SPIRV-LLVM-Translator, then create a PR with the updated commit in `lib/Target/SPIRV/spirv-llvm-translator.conf`, like how it is done in this PR.

**Comment by whitneywhtsang** [comment]
> Find the last commit that can pass all Triton tests in https://github.com/KhronosGroup/SPIRV-LLVM-Translator, then create a PR with the updated commit in `lib/Target/SPIRV/spirv-llvm-translator.conf`, like how it is done in this PR.

Created https://github.com/intel/intel-xpu-backend-for-triton/issues/447 to track it.

**Review by pbchekin — APPROVED** [review]

**Pull request merged**
