### PR TITLE
[DOC] Updated wiki to have instructions for building triton on NV Machine

### PR DESCRIPTION
**Pull request by prathams417**
Updating wiki to include instructions to compile and run triton on an Nvidia machine. These changes will **not** be merged upon approval, they will be added to the wiki.

### CODE REVIEW

**Comment by pbchekin** [comment]
What is RTX6000-Lab and why it needs to be in a public repository?

**Comment by whitneywhtsang** [comment]
> What is RTX6000-Lab and why it needs to be in a public repository?

It is a NV machine we have access to. It is useful to have a document on how to build on it, so we can use it to understand how passes behave on NV, and help us debug issues on XPU. The document doesn't need to in a public repository, do you have suggestion on where would be a good location to keep it?

**Comment by pbchekin** [comment]
@prathams417 we discussed this briefly with @whitneywhtsang and decided it would be good to have this document in the internal wiki at the moment. Please DM me for the details.

**Comment by prathams417** [comment]
https://wiki.ith.intel.com/display/Triton/Compiling+Triton+on+Nvidia+Machines

**Review by etiotto — APPROVED** [review]
LGTM

**Comment by pbchekin** [comment]
The content has been moved to the internal wiki, this PR is no longer needed.

**Pull request closed without merging**
