### PR TITLE
Add GenISA library.

### PR DESCRIPTION
**Pull request by chengjunlu**
Add the pre-build static gen ISA library to the XPU backend.

### CODE REVIEW

**Comment by etiotto** [comment]
We have a copy of `libGenISAIntrinsics.a` in the Intel LLVM repository already because the GENX dialect (part of the Intel LLVM monorepo) issues calls to IGC builtins.  This PR adds *another* copy to the Triton project which then causes dual maintenance. So this is not ideal. 

IMO Triton should avoid issuing calls to IGC builtin function *directly* and should instead lower to the GENX dialect. If a particular operation is missing from the GENX dialect we can add it. That way other open source project (not just Triton) would benefit from having required operation in the GENX dialect. 

We can discuss this approach in a team meeting perhaps ?

**Comment by chengjunlu** [comment]
> We have a copy of `libGenISAIntrinsics.a` in the Intel LLVM repository already because the GENX dialect (part of the Intel LLVM monorepo) issues calls to IGC builtins. This PR adds _another_ copy to the Triton project which then causes dual maintenance. So this is not ideal.
> 
> IMO Triton should avoid issuing calls to IGC builtin function _directly_ and should instead lower to the GENX dialect. If a particular operation is missing from the GENX dialect we can add it. That way other open source project (not just Triton) would benefit from having required operation in the GENX dialect.
> 
> We can discuss this approach in a team meeting perhaps ?

It seems we can simply remove the GenISA library dependency if the GenX dialect can cover it.

**Comment by etiotto** [comment]
> > We have a copy of `libGenISAIntrinsics.a` in the Intel LLVM repository already because the GENX dialect (part of the Intel LLVM monorepo) issues calls to IGC builtins. This PR adds _another_ copy to the Triton project which then causes dual maintenance. So this is not ideal.
> > IMO Triton should avoid issuing calls to IGC builtin function _directly_ and should instead lower to the GENX dialect. If a particular operation is missing from the GENX dialect we can add it. That way other open source project (not just Triton) would benefit from having required operation in the GENX dialect.
> > We can discuss this approach in a team meeting perhaps ?
> 
> It seems we can simply remove the GenISA library dependency if the GenX dialect can cover it.

> Give it a try. If there are missing GENX operations annotate what is missing in an issue and we can then address the issue by adding new operations to the GENX dialect plus related cleanup in this repository.

**Comment by chengjunlu** [comment]
> > > We have a copy of `libGenISAIntrinsics.a` in the Intel LLVM repository already because the GENX dialect (part of the Intel LLVM monorepo) issues calls to IGC builtins. This PR adds _another_ copy to the Triton project which then causes dual maintenance. So this is not ideal.
> > > IMO Triton should avoid issuing calls to IGC builtin function _directly_ and should instead lower to the GENX dialect. If a particular operation is missing from the GENX dialect we can add it. That way other open source project (not just Triton) would benefit from having required operation in the GENX dialect.
> > > We can discuss this approach in a team meeting perhaps ?
> > 
> > 
> > It seems we can simply remove the GenISA library dependency if the GenX dialect can cover it.
> 
> Give it a try. If there are missing GENX operations annotate what is missing in an issue and we can then address the issue by adding new operations to the GENX dialect plus related cleanup in this repository.

A new issue is created to track the GenISA library as part of the GenX dialect. I think we can close this PR.

**Pull request closed without merging**
