### PR TITLE
Enable test_store_constant_default_dtype

### LINKED ISSUE #1534: [test_core.py::test_store_constant_default_dtype] Fix interpreter UT failure on XPU
Upstream commit https://github.com/triton-lang/triton/commit/1b35f118fd532ea4d032883408ea5729118b7767 implemented implicit tensor conversion for assignment operators. The feature is tested with `test_core.py::test_store_constant_default_dtype`. 

This upstream commit causes interpreter UT failures, a workaround is added in https://github.com/intel/intel-xpu-backend-for-triton/pull/1533:
`python/triton/runtime/interpreter.py`:
```
        # FIXME: This is a temporary workaround to avoid compilation failures.
        self.rewritted_fn[self.fn] = self.fn
        return self.fn
```
UT `test_core.py::test_store_constant_default_dtype` fails due to the workaround:
```
    if is_interpreter():
        pytest.skip("FIXME: Incorrect result on XPU")
```

This issue is to remove the workaround, and reenabled `test_core.py::test_store_constant_default_dtype`.

### PR DESCRIPTION
**Pull request by YarShev**
Closes #1534.

### CODE REVIEW

**Review by whitneywhtsang — APPROVED** [review]
Cool that it just work now.

**Comment by YarShev** [comment]
@whitneywhtsang, IIUC, the kernel function is executed twice: 1) in [L1153](https://github.com/intel/intel-xpu-backend-for-triton/blob/0f48a0d42960403dad4d7346cefb26bad85149ab/python/triton/runtime/interpreter.py#L1153C21-L1153C38) and 2) in [L1095](https://github.com/intel/intel-xpu-backend-for-triton/blob/0f48a0d42960403dad4d7346cefb26bad85149ab/python/triton/runtime/interpreter.py#L1095). Could you explain why is so?

**Comment by whitneywhtsang** [comment]
> @whitneywhtsang, IIUC, the kernel function is executed twice: 1) in [L1153](https://github.com/intel/intel-xpu-backend-for-triton/blob/0f48a0d42960403dad4d7346cefb26bad85149ab/python/triton/runtime/interpreter.py#L1153C21-L1153C38) and 2) in [L1095](https://github.com/intel/intel-xpu-backend-for-triton/blob/0f48a0d42960403dad4d7346cefb26bad85149ab/python/triton/runtime/interpreter.py#L1095). Could you explain why is so?

From adding a print line in a test case, we can see that it is only executed in [L1095](https://github.com/intel/intel-xpu-backend-for-triton/blob/0f48a0d42960403dad4d7346cefb26bad85149ab/python/triton/runtime/interpreter.py#L1095).

**Comment by YarShev** [comment]
Yes, print from the kernel happens only once but the flow is the following. We convert the source code of the kernel to ast, compile and execute it in [L1153](https://github.com/intel/intel-xpu-backend-for-triton/blob/0f48a0d42960403dad4d7346cefb26bad85149ab/python/triton/runtime/interpreter.py#L1153C21-L1153C38). And then the kernel gets executed again in [L1095](https://github.com/intel/intel-xpu-backend-for-triton/blob/0f48a0d42960403dad4d7346cefb26bad85149ab/python/triton/runtime/interpreter.py#L1095). Why is the kernel not executed in the first case? What am I missing on?

**Comment by whitneywhtsang** [comment]
Let's take `test_store_constant_default_dtype` as an example, the `compiled_code` is 
```
def kernel(output_ptr, n_elements, BLOCK_SIZE: tl.constexpr):
    offsets = triton.language.core._to_tensor(tl.program_id(axis=0) * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE), interpreter_builder, False)
    mask = triton.language.core._to_tensor(offsets < n_elements, interpreter_builder, False)
    value = triton.language.core._to_tensor(1, interpreter_builder, False)
    output = triton.language.core._to_tensor(tl.full([BLOCK_SIZE], value=value, dtype=value.dtype), interpreter_builder, False)
    tl.store(output_ptr + offsets, output, mask=mask)
```
It defines a kernel. Executing the `compiled_code` doesn't actually runs the `kernel` function.

**Comment by YarShev** [comment]
> Executing the compiled_code doesn't actually runs the kernel function.

Why does it not run the kernel and what does it actually mean "executing the compiled_code"?

**Comment by whitneywhtsang** [comment]
> > Executing the compiled_code doesn't actually runs the kernel function.
> 
> Why does it not run the kernel and what does it actually mean "executing the compiled_code" in this case?

I believe it is to define the transformed kernel, which can be executed in [L1095](https://github.com/intel/intel-xpu-backend-for-triton/blob/0f48a0d42960403dad4d7346cefb26bad85149ab/python/triton/runtime/interpreter.py#L1095).

**Comment by YarShev** [comment]
@whitneywhtsang, my understanding is we transform the source code of the kernel to a more suitable form (triton specific), execute (using exec) it and cache the function call (python itself does this). If we look at transformed_ast, we will see print statement is still there.

```bash
pp ast.unparse(transformed_ast)

('def kernel(output_ptr, n_elements, BLOCK_SIZE: tl.constexpr):\n'
 "    print('AAA')\n"
 '    offsets = triton.language.core._to_tensor(tl.program_id(axis=0) * '
 'BLOCK_SIZE + tl.arange(0, BLOCK_SIZE), interpreter_builder, False)\n'
 '    mask = triton.language.core._to_tensor(offsets < n_elements, '
 'interpreter_builder, False)\n'
 '    value = triton.language.core._to_tensor(1, interpreter_builder, False)\n'
 '    output = triton.language.core._to_tensor(tl.full([BLOCK_SIZE], '
 'value=value, dtype=value.dtype), interpreter_builder, False)\n'
 '    tl.store(output_ptr + offsets, output, mask=mask)')
```

If my undertanding is correct, I wonder why we need this intermediate step of execution? Why can't we just keep the compiled version of the code and the execute it only once?

**Pull request merged**
