### PR TITLE
Remove unnecessary change in common code

### PR DESCRIPTION
**Pull request by etiotto**

### CODE REVIEW

**Comment by etiotto** [comment]
Changes can be done upstream, see https://github.com/intel/intel-xpu-backend-for-triton/issues/2065

**Comment by etiotto** [comment]
Changes to `LinerLayoutConversion.cpp` can be done upstream, see issue #2066.

**Comment by etiotto** [comment]
> Changes to `LinerLayoutConversion.cpp` can be done upstream, see issue #2066.

This is done via upstream PR: https://github.com/triton-lang/triton/pull/4617

**Review by chengjunlu — APPROVED** [review]

**Comment by whitneywhtsang** [comment]
> Changes to `ops.cpp` can be done upstream, see #2065

Upstreamed in https://github.com/triton-lang/triton/commit/3b2468a54efe7f239b40745b713aa3d082f00346.

**Pull request merged**
