### PR TITLE
Fix `test_scan_layouts[True-1-src_layout10-64-32]` on LTS driver

### PR DESCRIPTION
**Pull request by anmyachev**

### CODE REVIEW

**Comment by anmyachev** [comment]
@whitneywhtsang this test produces many of the same constants, such as:
```bash
@assertFunc_447 = internal addrspace(1) constant [8 x i8] c"unknown\00"
@assertFile_447 = internal addrspace(1) constant [87 x i8] c".../pytest-0/test_scan_layouts_True_1_src_l0/test_scan_layouts.ttgir\00"
@assertMessage_447 = internal addrspace(1) constant [18 x i8] c"overflow detected\00"
```
Does it make sense to compare the contents of constants before adding them to reduce their total number? If so, I would like to try to implement it.

**Comment by whitneywhtsang** [comment]
> @whitneywhtsang this test produces many of the same constants, such as:
> 
> ```shell
> @assertFunc_447 = internal addrspace(1) constant [8 x i8] c"unknown\00"
> @assertFile_447 = internal addrspace(1) constant [87 x i8] c".../pytest-0/test_scan_layouts_True_1_src_l0/test_scan_layouts.ttgir\00"
> @assertMessage_447 = internal addrspace(1) constant [18 x i8] c"overflow detected\00"
> ```
> 
> Does it make sense to compare the contents of constants before adding them to reduce their total number? If so, I would like to try to implement it.

Is it related to the test failure? Is it unique to Intel backend?

**Comment by anmyachev** [comment]
> Is it related to the test failure?

Not directly, I just noticed that there were a lot of identical objects.

> Is it unique to Intel backend?

The code is similar to the one used for the NVIDIA backend, I suppose so, but I haven't run it on their hardware.

**Comment by etiotto** [comment]
@anmyachev can you resolve the merge conflicts pls. Hope that doing so can fix the tests.

**Comment by anmyachev** [comment]
> @whitneywhtsang this test produces many of the same constants, such as:
> 
> ```shell
> @assertFunc_447 = internal addrspace(1) constant [8 x i8] c"unknown\00"
> @assertFile_447 = internal addrspace(1) constant [87 x i8] c".../pytest-0/test_scan_layouts_True_1_src_l0/test_scan_layouts.ttgir\00"
> @assertMessage_447 = internal addrspace(1) constant [18 x i8] c"overflow detected\00"
> ```
> 
> Does it make sense to compare the contents of constants before adding them to reduce their total number? If so, I would like to try to implement it.

Hi @etiotto, thanks for review!

I think the initial issue is already fixed, there is nothing useful in this pull request, I will close it. However, there is one unanswered question left here. Can I know what you think about this?

**Pull request closed without merging**
