### PR TITLE
Use select for masked single element load

### PR DESCRIPTION
**Pull request by alexbaden**
As part of my investigation into #1721, I found an opportunity to remove some branches in certain kernels by removing a predicated load in favor of a load+select. The nvidia path does something similar - the difference there is they can emit a masked load instruction. This patch removes quite a bit of branching from the sample kernel from #1721 reducing runtime from 0.090ms to 0.067ms. 

I intend to do more testing as well as look for other optimizations in similar kernels, so I am marking this as draft for now but putting it up so it can run through CI (my local env is not setup for testing against IPEX).

### CODE REVIEW

**Comment by chengjunlu** [comment]
@alexbaden 
If the IGC cannot optimize the branching with the prediction, and the load with mask can be good in performance.

Please use the GenISA instead of load the memory without protection. It may causes the page fault in GPU if the address is not valid.

Here is the gather load with mask in GenISA.
https://github.com/intel/intel-graphics-compiler/blob/0d1c68f522be3684fa2a671f042bf5794dda1849/IGC/GenISAIntrinsics/generator/input/Intrinsic_definitions.yml#L9055

Here is the scatter store with the mask in GenISA.
https://github.com/intel/intel-graphics-compiler/blob/0d1c68f522be3684fa2a671f042bf5794dda1849/IGC/GenISAIntrinsics/generator/input/Intrinsic_definitions.yml#L9234

**Comment by whitneywhtsang** [comment]
Had a discussion with IGC team, next step is for us to evaluate performance impact with the GenISA intrinsic, and open a IGC issue to have it exposed if it gives performance gain.

**Comment by etiotto** [comment]
@alexbaden are you going to measure the performance impact of using the proposed IGC GenISA functions for that workload ?

**Comment by alexbaden** [comment]
We tried the IGC function, but it is meant for masked loads for the render engine and not the GPGPU. 
Using select on the other constant / load value seems to work in local testing, but we are not sure yet what the implications are of having a load instruction on what may be a null ptr / uninitialized memory, even if the result of that load is not used. 
I did try selecting the ptr values (putting `other` into its own alloca), but the ptr has to be in global memory so this ended up being quite slow. 
The current PR calls select on the value, not the ptr. Let's see if it passes CI and then decide how to proceed.

**Pull request closed without merging**
