### PR TITLE
Remove `ArithDivFOpLowering` pattern

### PR DESCRIPTION
**Pull request by whitneywhtsang**
Verified IGC is able to perform the optimization on agama 950.

### CODE REVIEW

**Comment by Dewei-Wang-sh** [comment]
any flag to enable it? what is IGC's default behaviour

**Comment by whitneywhtsang** [comment]
> any flag to enable it? what is IGC's default behaviour

No flags are needed, it is enabled by default. For FA, from the last LLVMIR file `codegen.ll`, I only see `%2 = fdiv 1, %1` follow by `mul %0, %2`.

**Comment by Dewei-Wang-sh** [comment]
> > any flag to enable it? what is IGC's default behaviour
> 
> No flags are needed, it is enabled by default. For FA, from the last LLVMIR file `codegen.ll`, I only see `%2 = fdiv 1, %1` follow by `mul %0, %2`.

so we will not have any fdiv, right?

**Review by Dewei-Wang-sh — APPROVED** [review]
lgtm

**Review by jopperm — APPROVED** [review]

**Review by victor-eds — APPROVED** [review]

**Review by etiotto — APPROVED** [review]

**Pull request merged**
