### PR TITLE
Add Wave ops in warp reduction.

### PR DESCRIPTION
**Pull request by chengjunlu**
Use the GenISA WaveAll and WaveCluster  in warp horizontal reduce.

### CODE REVIEW

**Comment by etiotto** [comment]
I think we should have an operation in the TritonGEN dialect for WaveAll and WaveCluster. I discussed the design of that operation yesterday with @whitneywhtsang.  I'm hoping she can create that operation and then we generate it in Triton.

**Comment by FMarno** [comment]
> I think we should have an operation in the TritonGEN dialect for WaveAll and WaveCluster. I discussed the design of that operation yesterday with @whitneywhtsang. I'm hoping she can create that operation and then we generate it in Triton.

It will likely also be helpful to add the [WavePrefix](https://github.com/intel/intel-graphics-compiler/blob/ed95d236c13bd62a3217b9f398f7136f0153afcc/IGC/GenISAIntrinsics/Intrinsic_definitions.py#L693C4-L693C5) intrinsic for scans (going by the small bit of documentation).

**Comment by chengjunlu** [comment]
> I think we should have an operation in the TritonGEN dialect for WaveAll and WaveCluster. I discussed the design of that operation yesterday with @whitneywhtsang. I'm hoping she can create that operation and then we generate it in Triton.

I will create a new PR based on the TritonGen operation.

**Comment by chengjunlu** [comment]
> > I think we should have an operation in the TritonGEN dialect for WaveAll and WaveCluster. I discussed the design of that operation yesterday with @whitneywhtsang. I'm hoping she can create that operation and then we generate it in Triton.
> 
> It will likely also be helpful to add the [WavePrefix](https://github.com/intel/intel-graphics-compiler/blob/ed95d236c13bd62a3217b9f398f7136f0153afcc/IGC/GenISAIntrinsics/Intrinsic_definitions.py#L693C4-L693C5) intrinsic for scans (going by the small bit of documentation).

I created an issue to track this new requirements.
https://github.com/intel/intel-xpu-backend-for-triton/issues/1216

**Comment by Dewei-Wang-sh** [comment]
> I think we should have an operation in the TritonGEN dialect for WaveAll and WaveCluster. I discussed the design of that operation yesterday with @whitneywhtsang. I'm hoping she can create that operation and then we generate it in Triton.

@whitneywhtsang @etiotto add an op in tritongen for attention, FYI.
https://github.com/Dewei-Wang-sh/intel-xpu-backend-for-triton/commit/8670e5c072c6939b997009d3fb31010ebdc9b9b0#diff-22fc078e0ae2b9f9c2ee859630bfbd1092802ce694665ffa78a27d0a6464fa01

**Comment by whitneywhtsang** [comment]
> > I think we should have an operation in the TritonGEN dialect for WaveAll and WaveCluster. I discussed the design of that operation yesterday with @whitneywhtsang. I'm hoping she can create that operation and then we generate it in Triton.
> 
> @whitneywhtsang @etiotto add an op in tritongen for attention, FYI. [Dewei-Wang-sh@8670e5c#diff-22fc078e0ae2b9f9c2ee859630bfbd1092802ce694665ffa78a27d0a6464fa01](https://github.com/Dewei-Wang-sh/intel-xpu-backend-for-triton/commit/8670e5c072c6939b997009d3fb31010ebdc9b9b0#diff-22fc078e0ae2b9f9c2ee859630bfbd1092802ce694665ffa78a27d0a6464fa01)

I am working on https://github.com/intel/intel-xpu-backend-for-triton/pull/1214, will put you as reviewer once it is ready, so you can check if it misses any features you need for your case.

**Comment by Dewei-Wang-sh** [comment]
> > > I think we should have an operation in the TritonGEN dialect for WaveAll and WaveCluster. I discussed the design of that operation yesterday with @whitneywhtsang. I'm hoping she can create that operation and then we generate it in Triton.
> > 
> > 
> > @whitneywhtsang @etiotto add an op in tritongen for attention, FYI. [Dewei-Wang-sh@8670e5c#diff-22fc078e0ae2b9f9c2ee859630bfbd1092802ce694665ffa78a27d0a6464fa01](https://github.com/Dewei-Wang-sh/intel-xpu-backend-for-triton/commit/8670e5c072c6939b997009d3fb31010ebdc9b9b0#diff-22fc078e0ae2b9f9c2ee859630bfbd1092802ce694665ffa78a27d0a6464fa01)
> 
> I am working on #1214, will put you as reviewer once it is ready, so you can check if it misses any features you need for your case.

great, this is the design align to our current.

**Comment by whitneywhtsang** [comment]
The operator is added in TritonGEN dialect, please update the PR to use it.

**Pull request closed without merging**
