### PR TITLE
[Benchmark] Run xetla streamk gemm in benchmark

### PR DESCRIPTION
**Pull request by ESI-SYD**

### CODE REVIEW

**Comment by whitneywhtsang** [comment]
@ESI-SYD Performance from https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11230502839 is 240TFlops, the reported performance was 262TFlops, can you investigate why?
There are a lot of printouts like below, can they be cleaned up?
```
 problem size: (3072,3072), tiled_shape: (12,12), tiles: 144, dp_tiles: 96, sk_tiles: 48, iters_per_tile: 128, num_workgroups: 128, dp_workgroups: 96, dp_waves: 3, sk_groups_per_region: 32, sk_regions: 1, sk_waves: 1, sk_iters_per_normal_group: 192, sk_big_groups_per_region: 0, avail_xecores: 32

Local range: {1, 8, 4} 
SK Score: 51
```

**Comment by ESI-SYD** [comment]
> @ESI-SYD Performance from https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11230502839 is 240TFlops, the reported performance was 262TFlops, can you investigate why? There are a lot of printouts like below, can they be cleaned up?
> 
> ```
>  problem size: (3072,3072), tiled_shape: (12,12), tiles: 144, dp_tiles: 96, sk_tiles: 48, iters_per_tile: 128, num_workgroups: 128, dp_workgroups: 96, dp_waves: 3, sk_groups_per_region: 32, sk_regions: 1, sk_waves: 1, sk_iters_per_normal_group: 192, sk_big_groups_per_region: 0, avail_xecores: 32
> 
> Local range: {1, 8, 4} 
> SK Score: 51
> ```

Let me check, previously I can get ~252 locally

**Comment by ESI-SYD** [comment]
Try to disable prints https://github.com/intel/xetla/pull/54

**Comment by whitneywhtsang** [comment]
What has changed? Is performance good now? Print disabled?

**Comment by ESI-SYD** [comment]
> What has changed? Is performance good now? Print disabled?

xecores increased, 251.6 now, 96% , print disable change not landed (looks like not activate in their public repo). 

https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11338429336/job/31531618981

**Comment by ESI-SYD** [comment]
Note: Pre-commit checks failure not releated to this PR.

**Review by chengjunlu — APPROVED** [review]

**Comment by whitneywhtsang** [comment]
In https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11338429336, I see stream-k performance is only 103TFlops.

**Comment by ESI-SYD** [comment]
> In https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11338429336, I see stream-k performance is only 103TFlops.

```
        M       K       N   Triton-GB/s    XeTLA-GB/s  Triton-GB/s-min  XeTLA-GB/s-min  Triton-GB/s-max  XeTLA-GB/s-max  Triton-TFlops  XeTLA-TFlops  Triton-TFlops-min  XeTLA-TFlops-min  Triton-TFlops-max  XeTLA-TFlops-max  Triton-CV  XeTLA-CV
0  3072.0  4096.0  3072.0  5.033170e+07  5.033177e+07     5.033169e+07    5.033173e+07     5.033170e+07    5.033179e+07     103.746892    251.641847          93.622131        168.239498         110.720402        280.920817   0.054009  0.174175

```

**Comment by whitneywhtsang** [comment]
> > In https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11338429336, I see stream-k performance is only 103TFlops.
> 
> ```
>         M       K       N   Triton-GB/s    XeTLA-GB/s  Triton-GB/s-min  XeTLA-GB/s-min  Triton-GB/s-max  XeTLA-GB/s-max  Triton-TFlops  XeTLA-TFlops  Triton-TFlops-min  XeTLA-TFlops-min  Triton-TFlops-max  XeTLA-TFlops-max  Triton-CV  XeTLA-CV
> 0  3072.0  4096.0  3072.0  5.033170e+07  5.033177e+07     5.033169e+07    5.033173e+07     5.033170e+07    5.033179e+07     103.746892    251.641847          93.622131        168.239498         110.720402        280.920817   0.054009  0.174175
> ```

Opps, I was looking at the wrong column.

**Review by whitneywhtsang — APPROVED** [review]
Please create an issue to track the removal of the prints.

**Comment by ESI-SYD** [comment]
> Please create an issue to track the removal of the prints.

https://github.com/intel/intel-xpu-backend-for-triton/issues/2489

**Comment by etiotto** [comment]
@ESI-SYD reminder, the pre-commit is failing.

**Pull request merged**
