### PR TITLE
Update PyTorch upstream pin to the head of release/2.4

### LINKED ISSUE #1719: Update pinned commit id for upstream PyTorch
The latest commit for PyTorch 2.4.

### PR DESCRIPTION
**Pull request by pbchekin**
Fixes #1719.

### CODE REVIEW

**Comment by pbchekin** [comment]
47 failed core tests with PyTorch 2.4:
https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10152105924/job/28072771079

10 failed core tests with PyTorch main:
https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10140531373/job/28035928660

**Comment by anmyachev** [comment]
@pbchekin Should we update `TORCH_XPU_OPS_COMMIT` to the version used in pytorch 2.4?https://github.com/pytorch/pytorch/blob/d990dada86a8ad94882b5c23e859b88c0c255bda/third_party/xpu.txt

**Comment by pbchekin** [comment]
> @pbchekin Should we update `TORCH_XPU_OPS_COMMIT` to the version used in pytorch 2.4?https://github.com/pytorch/pytorch/blob/d990dada86a8ad94882b5c23e859b88c0c255bda/third_party/xpu.txt

Good point! Will do.

**Comment by pbchekin** [comment]
> @pbchekin Should we update `TORCH_XPU_OPS_COMMIT` to the version used in pytorch 2.4?

Done

**Review by anmyachev — APPROVED** [review]
LGTM!

**Comment by pbchekin** [comment]
40 failed tests with PyTorch 2.4:
https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10170567352/job/28129928609#step:17:24436

1 failed test with PyTorch main:
https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10170445682/job/28129585386#step:17:22112

**Pull request merged**
