### PR TITLE
Update bfloat16 conversion property

### PR DESCRIPTION
**Pull request by anmyachev**
The corresponding change in https://github.com/pytorch/pytorch/pull/131738/commits/08860b26f18e78efa14f033f33f0199ac0f66370

Blocked on https://github.com/intel/intel-extension-for-pytorch/pull/694

### CODE REVIEW

**Comment by alexbaden** [comment]
Linking to PyTorch PR which introduced property: https://github.com/pytorch/pytorch/pull/131738

**Review by alexbaden — APPROVED** [review]
Per @vlad-penkin we should merge this without the IPEX changes as IPEX is not expected to be used on the client GPUs (where this matters).

**Review by whitneywhtsang — CHANGES_REQUESTED** [review]
LGTM, request changes to update IPEX pin.

**Comment by vlad-penkin** [comment]
@whitneywhtsang ipex PR is not required and is not blocking. Could you please approve the PR.

**Review by vlad-penkin — APPROVED** [review]
LGTM

**Review by whitneywhtsang — APPROVED** [review]
Since the default value is True, we can put this PR in, but we should still update IPEX pin when it is available.

**Comment by anmyachev** [comment]
> Since the default value is True, we can put this PR in, but we should still update IPEX pin when it is available.

https://github.com/intel/intel-xpu-backend-for-triton/pull/1965

**Pull request merged**
