### PR TITLE
Fix `test_chained_reductions`

### LINKED ISSUE #2703: [UT] Fix `test_chained_reductions[in_shape0-perm0-red_dims0]`
The unit test is added in https://github.com/intel/intel-xpu-backend-for-triton/pull/2699.

### PR DESCRIPTION
**Pull request by etiotto**
Fixes #2703

### CODE REVIEW

**Review by whitneywhtsang — COMMENTED** [review]
Need to remove `test_chained_reductions` from skiplists.

**Review by victor-eds — COMMENTED** [review]
Question: are our changes to `ReduceOpToLLVM.cpp` in line with NVIDIA backend's implementation?

**Review by whitneywhtsang — APPROVED** [review]

**Comment by whitneywhtsang** [comment]
> Question: are our changes to `ReduceOpToLLVM.cpp` in line with NVIDIA backend's implementation?

Yes, it is similar to `lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp`.

**Comment by etiotto** [comment]
> Question: are our changes to `ReduceOpToLLVM.cpp` in line with NVIDIA backend's implementation?

yes

**Pull request merged**
