### PR TITLE
Update patches for PyTorch upstream

### PR DESCRIPTION
**Pull request by whitneywhtsang**
```
Fallback to CPU for XPU FP64 - https://github.com/pytorch/pytorch/pull/126516
Elapsed time - https://github.com/pytorch/pytorch/pull/126456
Device properties - https://github.com/pytorch/pytorch/pull/131738
```

### CODE REVIEW

**Comment by ZzEeKkAa** [comment]
It may not work till we align properties names. And I was also facing some problems with receiving properties, so I had to apply patch. Check these changes out: 
https://github.com/pytorch/pytorch/commit/bff2ac525c2893a0d1bf51bed910ba06eb9417b4 - receiving properties 
https://github.com/pytorch/pytorch/commit/751c7826bfea66a5e3c52207fa5a0d8b46efb9bb - name alignment

**Review by pbchekin — APPROVED** [review]

**Comment by whitneywhtsang** [comment]
Depends on https://github.com/intel/intel-xpu-backend-for-triton/pull/1788.

**Comment by whitneywhtsang** [comment]
@ZzEeKkAa https://github.com/intel/intel-xpu-backend-for-triton/pull/1788 is merged. Do we still need any other changes from your branch?

**Comment by ZzEeKkAa** [comment]
@whitneywhtsang no. https://github.com/pytorch/pytorch/commit/751c7826bfea66a5e3c52207fa5a0d8b46efb9bb was resolved by #1788 and https://github.com/pytorch/pytorch/commit/bff2ac525c2893a0d1bf51bed910ba06eb9417b4 was addressed in the PR itself.

**Review by ZzEeKkAa — APPROVED** [review]

**Pull request merged**
