### PR TITLE
[CI] show less verbose log and give failed summary for each commit id

### PR DESCRIPTION
**Pull request by AshburnLee**
Fix: https://github.com/intel/intel-xpu-backend-for-triton/issues/2302

Now we have a failed cases summary:
image
https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11009534190/job/30569394563

Note that there are no more detailed log for FAILED cases. so could not get exact error message for each cases.

### CODE REVIEW

**Comment by pbchekin** [comment]
The exact error message is not shown, there is only a list of failed tests.
```
2024-09-24T09:01:59.3474072Z cid: dc1221cd83e67efb94ec5c729f250bbe1d886707:
2024-09-24T09:01:59.3475958Z FAILED language/test_core.py::test_bitwise_op[1-int8-int8-|2]
2024-09-24T09:01:59.3477249Z FAILED language/test_core.py::test_bitwise_op[1-uint64-uint16-&3]
2024-09-24T09:01:59.3490394Z FAILED language/test_annotations.py::test_int_annotation[False-8]
...
```

**Comment by AshburnLee** [comment]
> The exact error message is not shown, there is only a list of failed tests.
> 
> ```
> 2024-09-24T09:01:59.3474072Z cid: dc1221cd83e67efb94ec5c729f250bbe1d886707:
> 2024-09-24T09:01:59.3475958Z FAILED language/test_core.py::test_bitwise_op[1-int8-int8-|2]
> 2024-09-24T09:01:59.3477249Z FAILED language/test_core.py::test_bitwise_op[1-uint64-uint16-&3]
> 2024-09-24T09:01:59.3490394Z FAILED language/test_annotations.py::test_int_annotation[False-8]
> ...
> ```

In our case, there is more detailed  error message in the original log. But I still capture the raw log for each failed cases:
~~~txt
Tests failed for translator commit dc1221cd83e67efb94ec5c729f250bbe1d886707
=================================== FAILURES ===================================
____________________ test/unit/language/test_annotations.py ____________________
[gw0] linux -- Python 3.10.14 /home/jovyan/conda/envs/junhui-py310/bin/python3
worker 'gw0' crashed while running 'test/unit/language/test_annotations.py::test_int_annotation[False-8]'
_______________________ test/unit/language/test_core.py ________________________
[gw6] linux -- Python 3.10.14 /home/jovyan/conda/envs/junhui-py310/bin/python3
worker 'gw6' crashed while running 'test/unit/language/test_core.py::test_bitwise_op[1-int32-uint64-^1]'
...
================== xdist: maximum crashed workers reached: 32 ==================
No warnings to write.
=========================== short test summary info ============================
Tests failed for translator commit 569972a61c86aa6892df443c6405283235022247
=================================== FAILURES ===================================
_______________________ test/unit/language/test_core.py ________________________
[gw2] linux -- Python 3.10.14 /home/jovyan/conda/envs/junhui-py310/bin/python3
worker 'gw2' crashed while running 'test/unit/language/test_core.py::test_bin_op[1-uint32-bfloat16-/]'
_______________________ test/unit/language/test_core.py ________________________
[gw6] linux -- Python 3.10.14 /home/jovyan/conda/envs/junhui-py310/bin/python3
worker 'gw6' crashed while running 'test/unit/language/test_core.py::test_bitwise_op[1-int32-uint64-^1]'
____________________ test/unit/language/test_annotations.py ____________________
[gw0] linux -- Python 3.10.14 /home/jovyan/conda/envs/junhui-py310/bin/python3
worker 'gw0' crashed while running 'test/unit/language/test_annotations.py::test_int_annotation[False-8]'
...
~~~

`spirv-llvm-translator.conf` has been updated to the latest cid, so there is no test run yet.

**Comment by pbchekin** [comment]
> In our case, there is no more detailed error message in the original log. But I still capture the raw log for each failed cases:

Right, this is what #2302 about, the error message is in the middle of a huge log.

**Review by pbchekin — CHANGES_REQUESTED** [review]
The problem identified in #2302 still persists.

**Comment by AshburnLee** [comment]
The PR has two purposes:

1. Reduce the verbose log.

Log for Run#47 (https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11009534190/job/30569394563) has lots of records: 
`Found link ...` & `Skipping link ...`, Which appears 70,000 times for 15 commit ids check, These logs can be eliminated by changing `pip install -vvv -e '.[build,tests]'` to `pip install -v -e '.[build,tests]'` in file `scripts/compile-triton.sh`. 

But Run#39 is special, log have extra extremely large amount of records: `warning: Double arithmetic operation is not supported on this platform with FP64 conversion emulation mode (poison FP64 kernels is enabled).`

It appeared 264,000+ times in run #39(the only run that have this records), this info appears before all commit ids check, and is related to building `intel-xpu-backend-for-triton/pytorch`.

And I've checked for run #33 #37 #41 #44 #49 #52 #62 #61, This particular record dose not appear in the logs.


2. Print the error message for each failed commit id.

Again, the above useless records appear before test running, so "the error message is in the middle of a huge log." is not true. This PR adds a Step to print each failed cid and the test error message (below is an example run):

~~~
Tests failed for translator commit dc1221cd83e67efb94ec5c729f250bbe1d886707:
=================================== FAILURES ===================================
____________________ test/unit/language/test_annotations.py ____________________
[gw0] linux -- Python 3.10.14 /home/jovyan/conda/envs/junhui-py310/bin/python3
worker 'gw0' crashed while running 'test/unit/language/test_annotations.py::test_int_annotation[False-8]'
_______________________ test/unit/language/test_core.py ________________________
[gw6] linux -- Python 3.10.14 /home/jovyan/conda/envs/junhui-py310/bin/python3
worker 'gw6' crashed while running 'test/unit/language/test_core.py::test_bitwise_op[1-int32-uint64-^1]'
...
================== xdist: maximum crashed workers reached: 32 ==================
No warnings to write.
=========================== short test summary info ============================
~~~

**Comment by AshburnLee** [comment]
So after applying this PR, 
1. Useless records: `Found link ...` & `Skipping link ...` will not appear in the logs.
2. Print the error message for each failed commit id has been enabled.
3. I'm not sure the special record during building `intel-xpu-backend-for-triton/pytorch`. No idea why this Pytorch was built in this particular Run.

**Comment by AshburnLee** [comment]
Hi @pbchekin , please have a look on my commend, and see if it meets our target

**Comment by AshburnLee** [comment]
Before this PR, the log of Run#74 (https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11336319478) has 25610 lines.

After applying this PR, log of Run#75 (https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11337498744) has 1994 lines.

Which approves this PR meets the target.

**Comment by pbchekin** [comment]
In the run https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11337498744/job/31529198127#step:12:1 "show summary of failed commit id" is empty, however there was a build error. Instead, logs should be grouped by commit id:
* Trying commit x1
* Build Triton
* Tests
* Trying commit x2
* ...

**Comment by pbchekin** [comment]
Closed in favor of #2551.

**Pull request closed without merging**
