### PR TITLE
Remove redundant local target-dependent code

### PR DESCRIPTION
**Pull request by kurapov-peter**
This one deals with all the switches on target. Will do patterns separately.

### CODE REVIEW

**Comment by whitneywhtsang** [comment]
lit tests currently use intel version of the passes, so we still need to keep `target`, until we can invoke passes in different backend in lit tests.

**Comment by kurapov-peter** [comment]
I think we should run neither passes nor tests for a different backend. Let's just fix that and remove the target.

**Comment by etiotto** [comment]
Cleaning up the code is great, but we need to maintain the ability to generate the LLVM IR for either the NVidia or the PVC targets by using a command line option (currently `--convert-triton-gpu-to-llvm="target=genx|nvvm"). I often use that capability to compare the code generated for NVidia.

**Comment by ienkovich** [comment]
> Cleaning up the code is great, but we need to maintain the ability to generate the LLVM IR for either the NVidia or the PVC targets by using a command line option (currently `--convert-triton-gpu-to-llvm="target=genx|nvvm"). I often use that capability to compare the code generated for NVidia.

IIUC you would simply use different pass names to do that from now on. There is no reason to support lowering for NVidia in our copy of passes. This path is not even tested.

**Comment by whitneywhtsang** [comment]
> IIUC you would simply use different pass names to do that from now on. There is no reason to support lowering for NVidia in our copy of passes. This path is not even tested.

If we can use different pass names to do that, it is enough, and I agree is a good idea to not support lowering for NVidia in our copy of passes. However, currently there aren't different pass names that can be invoked in command line that I am aware of.

**Comment by ienkovich** [comment]
> If we can use different pass names to do that, it is enough, and I agree is a good idea to not support lowering for NVidia in our copy of passes. However, currently there aren't different pass names that can be invoked in command line that I am aware of.

This is because `registerConvertTritonGPUToLLVMPass` was replaced with `registerConvertTritonIntelGPUToLLVMPass` in `registerTritonDialects`. We should be able to have both of them given they have different names.

**Comment by whitneywhtsang** [comment]
> This is because registerConvertTritonGPUToLLVMPass was replaced with registerConvertTritonIntelGPUToLLVMPass in registerTritonDialects. We should be able to have both of them given they have different names.

Can we please add the ability to use NVidia passes in command line before cleaning the code?

**Comment by ienkovich** [comment]
> Can we please add the ability to use NVidia passes in command line before cleaning the code?

It will be easier to do after some code clean-ups because this requires building both nvidia and intel plugins. Right now, nvidia plugin in our repo still has a lot of our modifications and conflicts with intel plugin (defines same passes and Target enum). 

Probably, it would be easier to start with removing unnecessary changes from nvidia plugin (simply use files from triton main branch?), then enable both plugins in our build to have all passes in triton-opt. Then clean-up intel plugin from nvidia-specific code.

**Comment by whitneywhtsang** [comment]
> Probably, it would be easier to start with removing unnecessary changes from nvidia plugin (simply use files from triton main branch?), then enable both plugins in our build to have all passes in triton-opt. Then clean-up intel plugin from nvidia-specific code.

I like this flow, the first step should have already been done. 
```
$ git diff 4d92c91c6c6969e18c70d61ac58718e78f7dbc43 third_party/nvidia/
<no diff>
```

**Comment by ienkovich** [comment]
> I like this flow, the first step should have already been done.
> 

Nice! I was looking into older sources then. So I'll try to make a patch to have both intel and nvidia passes in triton tools.

**Comment by ienkovich** [comment]
There is still a conflict on Target enum. Merge up to 2043509060830e657e9e9b7d99736e70c4fd620b where it was removed will help.

**Comment by whitneywhtsang** [comment]
> There is still a conflict on Target enum. Merge up to 2043509060830e657e9e9b7d99736e70c4fd620b where it was removed will help.

Merged up to 2043509060830e657e9e9b7d99736e70c4fd620b in https://github.com/intel/intel-xpu-backend-for-triton/pull/602.

**Comment by whitneywhtsang** [comment]
Done in https://github.com/intel/intel-xpu-backend-for-triton/pull/627.

**Pull request closed without merging**
